# Generated by Django 5.1.4 on 2024-12-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0002_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
