# Generated by Django 5.1.4 on 2024-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0006_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
